insert into user (user_id, email, gender, hashed_pwd, intro, user_name, photo, salt, telephone, department_id, class_id, group_id) values ('1', NULL, NULL, 'abc', 'A bad man', 'Chen', 'A photo', 'a salt', '12345678', 0, 10001, 3);
insert into department (id, dept_name) values (0, 'Computer Science');
insert into course (id, credit, intro, name, num_lessons_each_week, department_id) values ('20011', 2.0, 'An Description', 'Data Structure', 5, 0);
insert into course (id, credit, intro, name, num_lessons_each_week, department_id) values ('20012', 10.0, 'A difficult course', 'Software engineering', 4.5, 0);
insert into class (id, capacity, num_student, semester, year, course_id, teacher_id) values (10001, 100, 50, 'FIRST', 2017, '20011', 'root');
insert into class (id, capacity, num_student, semester, year, course_id, teacher_id) values (10003, 100, 50, 'SECOND', 2018, '20012', 'root');
insert into campus (id, name) values (1, 'Yuquan');
insert into building (id, name, campus_id) values (1, '7th Building', 1);
insert into classroom (id, capacity, name, building_id) values (1, 120, '101', 1);
insert into time_slot (id, type, classroom_id, class_id) values (1, 'MON_1_2', 1, 10001);