source campus.sql;
source building.sql;
source classroom.sql;
source department.sql;
source major.sql;
source user.sql;
source major_class.sql ;
source course.sql;
source class.sql;
source time_slot.sql;
source testsys.sql;
source question.sql;
